### PR TITLE
Bump build number

### PR DESCRIPTION
**Pull request by vincentmr**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by leofang** [comment]
Ah, yes, forgot to say, this is a multi output recipe, each output can/should have its own build number, e.g.
https://github.com/conda-forge/cuquantum-feedstock/blob/main/recipe/meta.yaml

**Comment by vincentmr** [comment]
> Ah, yes, forgot to say, this is a multi output recipe, each output can/should have its own build number

Thanks for pointing this out. I guess here only `pennylane-lightning-core` and `pennylane` would need a bump since `pennylane-core` does not depend on Kokkos. I bumped the build number throughout nevertheless, is that an issue? Or as long as it goes up ...

**Comment by vincentmr** [comment]
@conda-forge-admin, please rerender

**Comment by leofang** [comment]
Making it uniform for now is fine. We can bump individually in the future, as needed.

**Comment by leofang** [comment]
```
/home/conda/feedstock_root/build_artifacts/pennylane-suite_1692726396597/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/include/KokkosSparse_spmv_impl.hpp: In function 'void KokkosSparse::Impl::spmv_beta_transpose(typename YVector::const_value_type&, const AMatrix&, const XVector&, typename YVector::const_value_type&, const YVector&)':
/home/conda/feedstock_root/build_artifacts/pennylane-suite_1692726396597/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/include/KokkosSparse_spmv_impl.hpp:522:68: error: cannot call member function 'int Kokkos::OpenMP::impl_thread_pool_size() const' without object
  522 |       impl_thread_pool_size = Kokkos::OpenMP::impl_thread_pool_size();
      |                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~
```

**Pull request closed without merging**
